name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Misc
        run: |
          . ./init_env.sh
          make sync_env
      - name: Misc 2
        run: make check_all
      - name: Install dependencies
        run: pip install -r constraints.txt
      - name: Install package
        run: pip install --no-deps .
      - name: Run checks
        run: make check_all
      - name: Install poetry
        run: pip install -c constraints.txt poetry
      - name: Build distributions
        run: poetry build
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1